# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'cliente'},
        ),
    ]
