# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'fornecedor', 'verbose_name_plural': 'fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'servi\xe7o'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='servicereview',
            options={'verbose_name': 'avalia\xe7\xe3o', 'verbose_name_plural': 'avalia\xe7\xf5es'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='negotiated_price',
        ),
    ]
